[general]
fullscreen = false
early-exit = true
corner-roundness = 80
initial-tool = "brush"
copy-command = "wl-copy"
annotation-size-factor = 2
output-filename = "/tmp/test-%Y-%m-%d_%H:%M:%S.png"
action-on-enter = "save-to-clipboard"
save-after-copy = false
default-hide-toolbars = false
primary-highlighter = "block"
disable-notifications = false

[font]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[color-palette]
palette = [
  "#8aadf4", # Blue
  "#ed8796", # Red
  "#a6da95", # Green
  "#eed49f", # Yellow
  "#c6a0f6", # Mauve
  "#cad3f5", # White
]
